spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: username
      password: password
      database: test
      authentication-database: admin

app:
  jwt:
    secret: JWT_SECRET
    expirationMs: 86400000
